package:
  exclude:
    - dist/img/**
    - .vscode/**
    - bin/**
    # needed for dynamic builds
    - dist/**
    - public/**
    - test/**
    - coverage/**
    - .eslintrc
    - mocha.opts
    - circle.ymp
    - jsconfig.json
    - webpack.config.js
    # exclude node_modules
    - node_modules/aws-sdk/**
    - node_modules/aws-sdk/dist/aws-sdk-react-native.js
    - node_modules/babel/**
    - node_modules/babel-*/**
    - node_modules/babili-webpack-plugin/**
    - node_modules/base64-font-loader/**
    - node_modules/bulma/**
    - node_modules/bootstrap/**
    - node_modules/compression-webpack-plugin/**
    - node_modules/chai/**
    - node_modules/css-loader/**
    - node_modules/caniuse-db/**
    - node_modules/drafter/**
    - node_modules/eslint/**
    - node_modules/enzyme/**
    - node_modules/eslint-*/**
    - node_modules/express/**
    - node_modules/extract-text-webpack-plugin/**
    - node_modules/file-loader/**
    - node_modules/formsy-*/**
    - node_modules/istanbul/**
    - node_modules/jquery/**
    - node_modules/js-cookie/**
    - node_modules/js-yaml/**
    - node_modules/jsdoc-to-markdown/**
    - node_modules/jsonschema/**
    - node_modules/karma/**
    - node_modules/karma-*/**
    - node_modules/lambda-tester/**
    - node_modules/material-design-icons/**
    - node_modules/mocha/**
    - node_modules/mocha-*/**
    - node_modules/node-sass/**
    - node_modules/preact/**
    - node_modules/preact-*/**
    - node_modules/prg-form/**
    - node_modules/prg-editor/**
    - node_modules/protagonist/**
    - node_modules/react/**
    - node_modules/react-*/**
    - node_modules/roboto-fontface/**
    - node_modules/sass-loader/**
    - node_modules/sinon/**
    - node_modules/style-loader/**
    - node_modules/tether/**
    - node_modules/uglify-js/**
    - node_modules/val-loader/**
    - node_modules/webpack/**
    - node_modules/webpack-*/**